### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by prestwich** [summa-tx/riemann-zeta#1]
- [x] Implement the keys table
- [x] Add `keys.py` with utility functions for accessing and storing keys
- [x] Implement the prevout table
- [x] Add `prevouts.py` with utility functions for accessing and storing prevouts
- [x] Lots of tests

**Comment by rrybarczyk** [comment]
Add the following functions to `prevouts.py`:

- [ ] `find_by_address`
- [ ] `find_by_txid`
- [ ] `find_by_outpoint`
- [ ] `find_unspents`

**Comment by prestwich** [comment]
addressed by #3
